### ISSUE TITLE
Table order for SQL Servers

### ISSUE THREAD

**Issue by frankvollebregt** [NicolaVerbeeck/flutter_local_storage_inspector#11]
Thanks for this plugin! It's very helpful to be able to inspect the file system, preferences, secure storage and of course my Drift database.

For the last one, I have many tables (thanks for the scroll bar, by the way!), which the plugin orders in a somewhat strange way: They are not ordered alphabetically, nor are the tables defined in the same file grouped together.

This is probably something related to how Drift internally identifies its tables, but I was wondering if it's possible for the plugin to support alphabetical ordering by table name or something similar, so that I can more easily find my tables in the list.

(The `drift_db_viewer` within the app shows the same order as this plugin, so I assume the cause lies somewhere within Drift)

**Comment by NicolaVerbeeck** [comment]
Yes indeed, drift does not expose this information as far as I know. I can add sorting though

**Comment by frankvollebregt** [comment]
That would be great, thank you!

**Comment by frankvollebregt** [comment]
I just made a discussion thread over at the Drift repo, asking if there is some rationale behind the current ordering

https://github.com/simolus3/moor/discussions/1671

**Comment by NicolaVerbeeck** [comment]
Sorting has been released to 0.1.5 of the drift inspector [drift_local_storage_inspector](https://pub.dev/packages/drift_local_storage_inspector)
